### PR TITLE
Wrong settings datatype

### PR DESCRIPTION
**Pull request by mervit**
Please merge this fix to master branche. Info is in commits.

datetimepicker was reding settings allways as true because (string)"false" is actuali logical true.

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
@akadlec Is there reason why this is not merged? I just stumbled upon same bug trying to disable meridiam format.

**Comment by akadlec** [comment]
@MartinMystikJonas conflicts

**Comment by MartinMystikJonas** [comment]
@akadlec So if I would prepare same fix based on current master it would be ok?

**Comment by MartinMystikJonas** [comment]
@akadlec Hi, do you know when would you have to time to check my PRs and merge them? I need this fixes deployed next week so I need to know if I should switch to fork of just wait. Thanks.

**Comment by akadlec** [comment]
no problem with merge, but this is similar to one PR you have opened.

**Pull request merged**
